# Breast Cancer Wisconsin (Diagnostic) Prediction
####Predict whether the cancer is benign or malignant

Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass. They describe characteristics of the cell nuclei present in the image. n the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server: ftp ftp.cs.wisc.edu cd math-prog/cpo-dataset/machine-learn/WDBC/

Also can be found on UCI Machine Learning Repository: https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Diagnostic%29

Attribute Information:

1) ID number 2) Diagnosis (M = malignant, B = benign) 3-32)

Ten real-valued features are computed for each cell nucleus:

a) radius (mean of distances from center to points on the perimeter) b) texture (standard deviation of gray-scale values) c) perimeter d) area e) smoothness (local variation in radius lengths) f) compactness (perimeter^2 / area - 1.0) g) concavity (severity of concave portions of the contour) h) concave points (number of concave portions of the contour) i) symmetry j) fractal dimension ("coastline approximation" - 1)

he mean, standard error and "worst" or largest (mean of the three largest values) of these features were computed for each image, resulting in 30 features. For instance, field 3 is Mean Radius, field 13 is Radius SE, field 23 is Worst Radius.

All feature values are recoded with four significant digits.

Missing attribute values: none

Class distribution: 357 benign, 212 malignant

In [0]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [0]:
# Import Dataset
dataset = pd.read_csv("/content/drive/My Drive/Web Data/Breast_Cancer.csv")

In [3]:
dataset.head() # It'll show first 5 Dataset

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [0]:
dataset.drop(['id'],1,inplace=True) # We dropped id column because we doen't want anymore

In [5]:
dataset.head() # After Deleting Id Column

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [6]:
dataset['diagnosis']=dataset['diagnosis'].map({'M':1,'B':0})
''' In our Dataset There Are 2 Types Of Cancer Stages
1) M = malignant
2) B = benign
we can't input as string that's why i mapped into 0 and 1 form ''' 


" In our Dataset There Are 2 Types Of Cancer Stages\n1) M = malignant\n2) B = benign\nwe can't input as string that's why i mapped into 0 and 1 form "

In [7]:
dataset

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0            1        17.99  ...          0.4601                  0.11890
1            1        20.57  ...          0.2750                  0.08902
2            1        19.69  ...          0.3613                  0.08758
3            1        11.42  ...          0.6638                  0.17300
4            1        20.29  ...          0.2364                  0.07678
..         ...          ...  ...             ...                      ...
564          1        21.56  ...          0.2060                  0.07115
565          1        20.13  ...          0.2572                  0.06637
566          1        16.60  ...          0.2218                  0.07820
567          1        20.60  ...          0.4087                  0.12400
568          0         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [8]:
dataset.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [0]:
X = dataset[['texture_mean','perimeter_mean','smoothness_mean','compactness_mean','symmetry_mean','radius_se','area_se']]
# We take Indepent variables in 1 (X)
y = dataset['diagnosis']
# Y is depended variable

In [0]:
# We splitting dataset into 2 parts, Train and Test
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y , test_size=1/3 , random_state=0)

In [11]:
X.shape

(569, 7)

In [12]:
y.shape

(569,)

In [13]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [14]:
X_train # This is our Independent train dataset

texture_mean  perimeter_mean  ...  radius_se  area_se
60          14.88           64.55  ...     0.5158   34.620
6           19.98          119.60  ...     0.4467   53.910
8           21.82           87.50  ...     0.3063   24.320
474         15.62           70.41  ...     0.1482    9.597
320         16.18           66.52  ...     0.3677   22.680
..            ...             ...  ...        ...      ...
277         19.98          120.90  ...     0.3283   36.740
9           24.04           83.97  ...     0.2976   23.940
359         18.32           59.82  ...     0.5079   30.480
192         18.22           60.73  ...     0.3539   21.690
559         23.93           74.52  ...     0.2388   16.970

[379 rows x 7 columns]

In [15]:
y_train   # This is our Dependent train dataset

60     0
6      1
8      1
474    0
320    0
      ..
277    1
9      1
359    0
192    0
559    0
Name: diagnosis, Length: 379, dtype: int64

In [16]:
X_test # This is our Independent test dataset

texture_mean  perimeter_mean  ...  radius_se  area_se
512         20.52           88.64  ...     0.3906    33.67
457         25.25           84.10  ...     0.2084    17.58
439         15.66           89.59  ...     0.2142    19.25
298         18.17           91.22  ...     0.2300    20.56
37          18.42           82.61  ...     0.1839    14.16
..            ...             ...  ...        ...      ...
299         23.09           66.85  ...     0.2868    20.56
347         14.74           94.87  ...     0.3428    29.06
502         16.32           81.25  ...     0.2577    18.49
56          18.57          125.50  ...     0.7275   102.50
144         14.97           68.26  ...     0.2525    17.74

[190 rows x 7 columns]

In [17]:
y_test # This is our Dependent test dataset

512    1
457    0
439    0
298    0
37     0
      ..
299    0
347    0
502    0
56     1
144    0
Name: diagnosis, Length: 190, dtype: int64

# Simple Linear Regression 
###(Just for fun) Don't do this

In [18]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
y_pred = model.predict(X_test)

In [0]:
from sklearn import metrics as mt
mse = mt.mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(mse)

In [21]:
RMSE

0.2837701063165978

***''' There are 6 steps '''***


1. import Algorithm
2. Create object of algo
3. fit data into it 

4. Predict the value from algo

5. Create confusion matrix 
6. Fit data into confusion matrix find accuracy


# Congrachulations ! In just 6 steps You'll Make your Breast Cancer detection Machine Learning Models


# Logistic Regression

In [22]:
from sklearn.linear_model import LogisticRegression # Step 1
modelLR = LogisticRegression(random_state=0) #Step 2
modelLR.fit(X_train,y_train)# Step 3

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_predLR = modelLR.predict(X_test) # Step 4

In [0]:
from sklearn.metrics import confusion_matrix # Step 5
cmlr = confusion_matrix(y_test,y_predLR) # step 6

In [25]:
cmlr

array([[117,   5],
       [ 17,  51]])

In [0]:
# 117+51 = 168 (Right Prediction)
# 17+5 = 22 (Wrong Prediction)
# Accuracy of Logistic Regression is : 88.42
# [(168*100) / 190] = 88.42

# Random Forest Classifier

In [27]:
from sklearn.ensemble import RandomForestClassifier
modelR = RandomForestClassifier(n_estimators = 10,criterion = 'entropy',random_state = 0)
modelR.fit(X_train,y_train)
 

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_predR = modelR.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predR)

In [30]:
cm

array([[119,   3],
       [ 10,  58]])

In [0]:
# 119+58 = 177 (Right Prediction)
# 10+3 = 13 (Wrong Prediction)
# Random Forest Accuracy Is : 93.15        
# [(177*100)/190] = 93.15

# Support Vector Classifier

In [32]:
from sklearn.svm import  SVC
modelSVM = SVC(kernel = 'linear',random_state = 0)
modelSVM.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
y_predSVM = modelSVM.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cmsvm = confusion_matrix(y_test,y_predSVM)

In [35]:
cmsvm

array([[113,   9],
       [  7,  61]])

In [0]:
# 113+61 = 174 (Right Prediction)
# 7+9 = 16 (Wrong Prediction)
# SVM Accuracy Is : 91.57       

# Decision Tree Classifier

In [37]:
from sklearn.tree import DecisionTreeClassifier
modelDTC = DecisionTreeClassifier(criterion = 'entropy')
modelDTC.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
y_predDTC = modelDTC.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cmdtc = confusion_matrix(y_test,y_predDTC)

In [40]:
cmdtc

array([[109,  13],
       [  9,  59]])

In [0]:
# 110+60 = 170 (Right Prediction)
# 12+8 = 20 (Wrong Prediction)
# SVM Accuracy Is : 89.47       

# K-NN Classifier

In [42]:
from sklearn.neighbors import KNeighborsClassifier
modelKNN  = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
modelKNN.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_predKNN = modelKNN.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cmknn = confusion_matrix(y_test,y_predKNN)

In [45]:
cmknn

array([[113,   9],
       [  4,  64]])

In [0]:
# 113+64 = 177 (Right prediction)
# 4+9 = 13 (Wrong Prediction)
# K-NN Accuracy is : 93.15

# Gaussian Naive bayes

In [47]:
from sklearn.naive_bayes import GaussianNB
modelGNB = GaussianNB()
modelGNB.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_predGNB = modelGNB.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cmgnb = confusion_matrix(y_test,y_predGNB)

In [50]:
cmgnb

array([[113,   9],
       [ 13,  55]])

In [0]:
# 113+55 = 168 (Right Prediction)
# 13+9 = 22 (Wrong Prediction)
# Accuracy of Gaussian Naive Bayes is : 88.42

In [0]:
from IPython.display import HTML, display
import tabulate
table = [
         ["Random Forest",(93.15)],
         ["K-Nearest Neibour",(93.15)],
         ["Support Vector Classifier ",(91.57)],
         ["Decision Tree",(89.47)],
         ["Logistic Regression",(88.42)],
         ["Gaussian Naive Bayes",(88.42)] ]


# Observation

In [53]:
display(HTML(tabulate.tabulate(table, tablefmt='html')))